### ISSUE TITLE
Specify the exact Youtube URL

### ISSUE THREAD

**Issue by vigneshPalanisamy87** [crunchersaspire/worshipsongs-db-dev#139]
Example for the song "Bless the Lord (Ten Thousand Reasons)"
Given URL : mediaUrl=https://www.youtube.com/watch?v=r3K3roEF36k
originalKey=G

Expected URL :  mediaUrl=https://www.youtube.com/watch?v=r3K3roEF36k

**Comment by sskjames** [comment]
Hi Vicky, the comments field shall have many properties separated by a newline char.
"originalKey" is one such property meant to display the musical key of the song. Our android app displays this key in Landscape mode.
