### ISSUE TITLE
Add the song "Anaathi Thevan Un Adaikkalamae"

### ISSUE THREAD

**Issue by sskjames** [crunchersaspire/worshipsongs-db-dev#16]
Title: Anaathi Thevan Un Adaikkalamae
Alternate title: Anathi Thevan Un Adaikkalame
Author: Saral Navoriji.

**Comment by noahantony** [comment]
{y}அநாதி தேவன் உன் அடைக்கலமே{/y}
Anaathi thaevan un ataikkalamae
{y}அவர் நித்திய புயங்கள் உன் ஆதாரமே{/y}
Avar niththiya puyangkal un aathaaramae

{y}இந்த தேவன் என்றென்றுமுள்ள{/y}
Intha thaevan entrenrumulla
{y}சதா காலமும் நமது தேவன் - மரண{/y}
Sathaa kaalamum namathu thaevan - marana
{y}பரியந்தம் நம்மை நடத்திடுவார்{/y}
Pariyantham nammai nataththituvaar

{y}காருண்யத்தாலே இழுத்துக்கொண்டார்{/y}
Kaarunyaththaalae izhuththukkontaar
{y}தூய தேவ அன்பே{/y}
Thooya thaeva anpae
{y}இவ்வனாந்திரத்தில் நயங்காட்டி உன்னை{/y}
Ivvanaanthiraththil nayangkaatti unnai
{y}இனிதாய் வருந்தி அழைத்தார்{/y}
Inithaay varunthi azhaiththaar

{y}கானக பாதை காரிருளில்{/y}
Kaanaka paathai kaarirulil
{y}தூய தேவ ஒளியே{/y}
Thooya thaeva oliyae
{y}அழுகை நிறைந்த பள்ளத்தாக்குகளை{/y}
Azhukai nitraintha pallaththaakkukalai
{y}அரும் நீருற்றாய் மாற்றினாரே{/y}
Arum neerutrraay maatrrinaarae

{y}கிருபை கூர்ந்து மனதுருகும்{/y}
Kirupai koornthu manathurukum
{y}தூய தேவ அன்பே{/y}
Thooya thaeva anpae
{y}உன் சமாதானத்தின் உடன்படிக்கை தனை{/y}
Un samaathaanaththin utanpatikkai thanai
{y}உண்மையாய் கர்த்தர் காத்துக் கொள்வார்{/y}
Unmaiyaay karththar kaaththuk kolvaar

{y}வறண்ட வாழ்க்கை செழித்திடுதே{/y}
Varanta vaazhkkai chezhiththituthae
{y}தூய தேவ அருளால்{/y}
Thooya thaeva arulaal
{y}நித்திய மகிழ்ச்சி தலைமேல் இருக்கும்{/y}
Niththiya makizhchchi thalaimael irukkum
{y}சஞ்சலம் தவிப்பும் ஓடிப்போம்{/y}
Sanjsalam thavippum oatippoam

{y}ஆனந்தம் பாடி திரும்பியே வா{/y}
Aanantham paati thirumpiyae vaa
{y}தூய தேவ பெலத்தால்{/y}
Thooya thaeva pelaththaal
{y}சீயோன் பர்வதம் உன்னைச் சேர்த்திடுவார்{/y}
Cheeyoan parvatham unnaich saerththituvaar
{y}சந்ததம் மகிழ்ச்சி அடைவாய்{/y}
Santhatham makizhchchi ataivaay

**Comment by sskjames** [comment]
Hi Noah, please add this song.

**Comment by noahantony** [comment]
Verse Order: C1 C2 V1 V2 V3 V4 V5
If there is any changes in verse order, then don't hesitate to change.

**Comment by sskjames** [comment]
Hi Noah, after every verse C2 and C1 should come.
And a verse length is pretty long, consider breaking it into V1 O1 and so on.

**Comment by sskjames** [comment]
TODO:

Chorus should repeat after every verse.

**Comment by sskjames** [comment]
Hi Noah, I will make the changes and commit.
