### ISSUE TITLE
Add the song "Akkini Neruppai Irangki Vaarum"

### ISSUE THREAD

**Issue by noahantony** [crunchersaspire/worshipsongs-db-dev#31]
Title: Akkini neruppai irangi varum
Alternate title: Akkini nerupai irangi varum
Author: Fr. S. J. Berchmans
Song Book: Jebathotta Jeyageethangal

**Comment by noahantony** [comment]
---[Chorus:1]---
{y}அக்கினி நெருப்பாய் இறங்கி வாரும்{/y}
Akkini neruppai irangi varum
{y}அபிஷேகம் தந்து வழி நடத்தும்{/y}
Abishegam thanthu vazhi nadathum
---[Verse:1]---
{y}முட்செடி நடுவே தோன்றினீரே{/y}
Mudchedi naduvae thoondrineerae
{y}மோசேயை அழைத்துப் பேசினீரே{/y}
Mosaeyai azhaithu pesineerae
{y}எகிப்து தேசத்துக்கு கூட்டிச் சென்றீரே{/y}
Eight theathuku kooti sentrirae
{y}எங்களை நிரப்பிப் பயன்படுத்தும்-இன்று{/y}
Engalai nirapi payanpaduthum - Intru
---[Verse:2]---
{y}எலியாவின் ஜெபத்திற்கு பதில் தந்தீரே{/y}
Eliyahvin jebathirku pathil thantheerae
{y}இறங்கி வந்தீர் அக்கினியாய்{/y}
Irangi vantheer akkiniyai
{y}இருந்த அனைத்தையும் சுட்டெரித்தீரே{/y}
Iruntha anaithaium suterutheerae
{y}எங்களின் குற்றங்களை எரித்துவிடும்{/y}
Engalin kuttangalai erithu vidum
---[Verse:3]---
{y}ஏசாயா நாவைத் தொட்டது போல{/y}
Easy naive thotathu pola
{y}எங்களின் நாவைத் தொட்டருளும்{/y}
Engalin naavai thotarulum
{y}யாரை நான் அனுப்புவேன் என்று சொன்னீரே{/y}
Yaarai naan anupuvaen entru soneerae
{y}எங்களை அனுப்பும் தேசத்திற்கு{/y}
Engalai anupum thesathirku
---[Verse:4]---
{y}அக்கினி மயமான நாவுகளாக{/y}
Akkini mayamana naavukalaga
{y}அப்போஸ்தலர் மேலே இறங்கி வந்தீரே{/y}
Apposthalar melae irangi vantheerae
{y}அந்நிய மொழியை பேச வைத்தீரே{/y}
Anniya mozhiyai pesa vatheerae
{y}ஆவியின் வரங்களால் நிரப்பினீரே{/y}
Aaviyin varangalal nirapineerae
---[Verse:5]---
{y}இரவு நேரத்தில் நெருப்புத் தூணாய்{/y}
Iravu nerathil neruppu thoonai
{y}இஸ்ரவேல் ஜனங்களை நடத்தினீரே{/y}
Isravel janangalai nadathineerae
{y}இருண்ட உலகத்தில் உம் சித்தம் செய்திட{/y}
Irunda ulagathil um sitham seithida
{y}எங்களை நிரப்பும் ஆவியினால்{/y}
Engalai nirappum aaviyinal

Verse order: C1 V1 C1 V2 C1 V3 C1 V4 C1 V5 C1

**Comment by sskjames** [comment]
Title should be: Akkini Neruppai Irangki Vaarum
I will review the Lyrics shortly.

**Comment by sskjames** [comment]
Here's the reviewed lyrics. You may add this song.

---[Chorus:1]---
{y}அக்கினி நெருப்பாய் இறங்கி வாரும்{/y}
Akkini neruppai irangki vaarum
{y}அபிஷேகம் தந்து வழி நடத்தும்{/y}
Abishegam thanthu vazhi nadaththum
---[Verse:1]---
{y}முட்செடி நடுவே தோன்றினீரே{/y}
Mutchedi naduvae thoandrineerae
{y}மோசேயை அழைத்துப் பேசினீரே{/y}
Moasaeyai azhaiththup pesineerae
{y}எகிப்து தேசத்துக்கு கூட்டிச் சென்றீரே{/y}
Ekipthu theasathukku kootich sendreerae
{y}எங்களை நிரப்பிப் பயன்படுத்தும்-இன்று{/y}
Engalai nirappip payanpaduththum - Intru
---[Verse:2]---
{y}எலியாவின் ஜெபத்திற்கு பதில் தந்தீரே{/y}
Eliyaavin jebathirkku pathil thantheerae
{y}இறங்கி வந்தீர் அக்கினியாய்{/y}
Irangki vantheer akkiniyaai
{y}இருந்த அனைத்தையும் சுட்டெரித்தீரே{/y}
Iruntha anaithaiyum sutteritheerae
{y}எங்களின் குற்றங்களை எரித்துவிடும்{/y}
Engkalin kutrrangkalai eriththu vidum
---[Verse:3]---
{y}ஏசாயா நாவைத் தொட்டது போல{/y}
Aeasaaya naavaith thottathu poala
{y}எங்களின் நாவைத் தொட்டருளும்{/y}
Engkalin naavaith thottarulum
{y}யாரை நான் அனுப்புவேன் என்று சொன்னீரே{/y}
Yaarai naan anuppuvaen entru sonneerae
{y}எங்களை அனுப்பும் தேசத்திற்கு{/y}
Engkalai anuppum thaesathirku
---[Verse:4]---
{y}அக்கினி மயமான நாவுகளாக{/y}
Akkini mayamaana naavukalaaga
{y}அப்போஸ்தலர் மேலே இறங்கி வந்தீரே{/y}
Appoasthalar maelae irangki vantheerae
{y}அந்நிய மொழியை பேச வைத்தீரே{/y}
Anniya mozhiyai paesa vaitheerae
{y}ஆவியின் வரங்களால் நிரப்பினீரே{/y}
Aaviyin varangkalaal nirappineerae
---[Verse:5]---
{y}இரவு நேரத்தில் நெருப்புத் தூணாய்{/y}
Iravu naerathil nerupputh thoonaai
{y}இஸ்ரவேல் ஜனங்களை நடத்தினீரே{/y}
Isravael janangkalai nadathineerae
{y}இருண்ட உலகத்தில் உம் சித்தம் செய்திட{/y}
Irunda ulakathil um siththam seithida
{y}எங்களை நிரப்பும் ஆவியினால்{/y}
Engkalai nirappum aaviyinaal
