### ISSUE TITLE
Add the song "Itho Manithargal Mathiyil"

### ISSUE THREAD

**Issue by noahantony** [crunchersaspire/worshipsongs-db-dev#34]
---[Chorus:1]---
{y}இதோ மனிதர்கள் மத்தியில்{/y}
Itho manithargal mathiyil
{y}வாசம் செய்பவரே{/y}
Vasam seibavarae
{y}எங்கள் நடுவிலே வசித்திட{/y}
Enggal naaduvile vasithidae
{y}விரும்பிடும் தெய்வமே(தேவனே){/y}
Virimbidum theivamae (devanae)

---[Verse:1]---
{y}உமக்கு சிங்காசனம் அமைத்திட{/y}
Umakku singhasanam ammaithida
{y}உம்மைத் துதிக்கின்றோம் இயேசுவே{/y}
Ummai thuthikindrom yesuvae
{y}பரிசுத்த அலங்காரத்துடனே{/y}
Parisutha alangarathudanae
{y}உம்மைத் தொழுகின்றோம் இயேசுவே{/y}
Ummai tholugindrom yesuvae

---[Verse:2]—
{y}எங்கள் மத்தியில் உலாவிடும்{/y}
Enggal mathiyil ulavidoam
{y}எங்களோடென்றும் வாசம் செய்யும்{/y}
Enggalodu yendrum vasam seiyum

**Comment by noahantony** [comment]
Title: Itho Manithargal Mathiyil
Alternate title: Itho Manithargal Mathiyil
Song Book: ?

**Comment by noahantony** [comment]
@sskjames Please review the song book and author. I am little confused.

**Comment by sskjames** [comment]
Title and Alternate title should be different. Change the title to: Ithoa Manithargal Maththiyil
Alternate title can remain as it is.

Song Book is not needed for this song. Use Song Books rarely. If the same Author is singing all the songs in an Album, then there is no point having an Album. Jebathoatta Jeyageethangal is an exception.

**Comment by sskjames** [comment]
What is the Verse Order?

**Comment by noahantony** [comment]
Title: Itho Manithargal Mathiyil
Alternate title: Ithoa Manithargal Maththiyil
Song Book: Melaanavar Vol-4
Sung by: Wesley Maxwell

**Comment by noahantony** [comment]
Verse order: C1 V1 V2
