### ISSUE TITLE
Add the song "Enthan Aathumavae Kartharai Thuthi"

### ISSUE THREAD

**Issue by noahantony** [crunchersaspire/worshipsongs-db-dev#35]
---[Chorus:1]---
{y}எந்தன் ஆத்துமாவே கர்த்தரைத் துதி{/y}
Enthan aathumavae kartharai thuthi
{y}கர்த்தரையே துதி{/y}
kartharaiae thuthi
{y}எந்தன் முழு உள்ளமே அவர் நாமத்தையே{/y}
Enthan muzhu ullamae avar naamathaiae
{y}என்றென்றும் ஸ்தோத்திரம்{/y}
Entrentum sthothari

---[Chorus:2]—
{y}அன்பின் கரத்தாலே தூக்கி எடுத்தீரே{/y}
Anbin karathalae thooki edutheerae
{y}கண்மலையில் என்னை நிறுத்தினீரே{/y}
kanmazhalai ennai nirutheenirae
{y}உம்மை துதித்திடும் புது பாடல் தந்தீரே{/y}
Ummai thuthithidum puthu pedal thanthirae
{y}ஆயிரம் நாவுகள் போதாதே{/y}
Aayiram naavukal pothathaey

---[Chorus:3]—
{y}என்னை கிருபையினால் முடி சூட்டினீரே{/y}
Ennai kirubaiyinal mudi sootineerae
{y}தோள்களின் மேலாய் உயர்த்தினீரே{/y}
Thozlkalin melai uyarthineerae
{y}உம் அன்பை நினைத்து நான் என்றும் துதிப்பேன்{/y}
Um anbai ninaithu nan entrum thuthipaen
{y}ஆயிரம் நாவுகள் போதாதே{/y}
Aayiram naavukal pothathaey

---[Chorus:4]—
{y}நாட்கள் நகர்ந்திட்டாலும் காலம் கடந்திட்டாலும்{/y}
Naatkal nagarnthitalum kalam kadanthitalum
{y}கர்த்தரே நீர் என்றும் மாறாதவர்{/y}
Kartharae neer entrum maarathavar
{y}உம் கிருபையை என்றும் எண்ணி நான் துதிப்பேனே{/y}
Um kirubaiyai entrum enni nan thuthipaenae
{y}ஆயிரம் நாவுகள் போதாதே{/y}
Aayiram naavukal pothathaey

**Comment by noahantony** [comment]
Title: Enthan Aathumavae Kartharai Thuthi
Alternate title: Enthan Aathumavae Kartharai Thuthi
Song Book: 10,000 Reasons
Author: Matt Redman

**Comment by noahantony** [comment]
Verse order: C1 C2 C3 C4

**Comment by noahantony** [comment]
@sskjames This is tamil and romanised version of 10,000 reasons songs. I am confused with the verse order. Can you please review the verse order?

**Comment by sskjames** [comment]
Change the alternate title to "Enthan Aathumave Kartharai Thuthi"
Alternate titles shall help the user to find a song with a different spelling.

Why do all the verses have the Chorus tag? Why not the Verse tag?

As far as the order is concerned, please check the English version.

There is no need for a song book for this song. Use Song Book only when there are large number of songs eg Keerthanaigal.

There are some spelling mistakes. Please proofread. கண்மலை should have been கன்மலை.

**Comment by noahantony** [comment]
---[Chorus:1]---
{y}எந்தன் ஆத்துமாவே கர்த்தரைத் துதி{/y}
Enthan aathumavae kartharai thuthi
{y}கர்த்தரையே துதி{/y}
kartharaiae thuthi
{y}எந்தன் முழு உள்ளமே அவர் நாமத்தையே{/y}
Enthan muzhu ullamae avar naamathaiae
{y}என்றென்றும் ஸ்தோத்திரம்{/y}
Entrentum sthothari

---[Chorus:2]—
{y}அன்பின் கரத்தாலே தூக்கி எடுத்தீரே{/y}
Anbin karathalae thooki edutheerae
{y}கன்மலையில் என்னை நிறுத்தினீரே{/y}
kanmazhalai ennai nirutheenirae
{y}உம்மை துதித்திடும் புது பாடல் தந்தீரே{/y}
Ummai thuthithidum puthu pedal thanthirae
{y}ஆயிரம் நாவுகள் போதாதே{/y}
Aayiram naavukal pothathaey

---[Chorus:3]—
{y}என்னை கிருபையினால் முடி சூட்டினீரே{/y}
Ennai kirubaiyinal mudi sootineerae
{y}தோள்களின் மேலாய் உயர்த்தினீரே{/y}
Thozlkalin melai uyarthineerae
{y}உம் அன்பை நினைத்து நான் என்றும் துதிப்பேன்{/y}
Um anbai ninaithu nan entrum thuthipaen
{y}ஆயிரம் நாவுகள் போதாதே{/y}
Aayiram naavukal pothathaey

---[Chorus:4]—
{y}நாட்கள் நகர்ந்திட்டாலும் காலம் கடந்திட்டாலும்{/y}
Naatkal nagarnthitalum kalam kadanthitalum
{y}கர்த்தரே நீர் என்றும் மாறாதவர்{/y}
Kartharae neer entrum maarathavar
{y}உம் கிருபையை என்றும் எண்ணி நான் துதிப்பேனே{/y}
Um kirubaiyai entrum enni nan thuthipaenae
{y}ஆயிரம் நாவுகள் போதாதே{/y}
Aayiram naavukal pothathaey

**Comment by noahantony** [comment]
Title: Enthan Aathumavae Kartharai Thuthi
Alternate title: Enthan Aathumave Kartharai Thuthi
Song Book: 10,000 Reasons
Author: Matt Redman
Verse order: C1 V1 C1 V2 C1 V3 C1
