### ISSUE TITLE
Add the song "Paathirar Neerae Yesuvae"

### ISSUE THREAD

**Issue by sskjames** [crunchersaspire/worshipsongs-db-dev#50]
Title: Paathirar Neerae Yesuvae
Alternate Title: Pathirar Neere Yesuve
Author: Robert Roy

**Comment by Jancy2523** [comment]
உமது கிருபை நிமித்தமும்
உமது உண்மையின் நிமித்தமும்
 
தேவனே உமது நாமத்தை துதிப்பேன்
என்றேன்றும் உமது நாமத்தை துதிப்பேன் -2

தடைகளை நிக்கும் தளபதியே 
என் நல்ல தேவன் நீரே
மதில்களை உடைக்கும் மகத்துவரே
என் வல்ல தேவன் நீரே -2
நான் மேலானவைகளை நாடுவேன்
மேன்மையானவையே நோக்குவேன் -2

உமது கிருபை நிமித்தமும்
உமது உண்மையின் நிமித்தமும்
தேவனே உமது நாமத்தை துதிப்பேன்
என்றேன்றும் உமது நாமத்தை துதிப்பேன் -2

தாழ்நத என்னை உயர்த்திடுவீர்
என் நல்ல தேவன் நீரே
மகிமையின் கனத்தால் முடிசூட்டுவீர்
என் வல்ல தேவன் நீரே -2
நான் மேலானவைகளை நாடுவேன்
மேன்மையானவையே நோக்குவேன் -2
உமது கிருபை நிமித்தமும்
உமது உண்மையின் நிமித்தமும்
தேவனே உமது நாமத்தை துதிப்பேன்
என்றேன்றும் உமது நாமத்தை துதிப்பேன் -2

உன்னதங்களில் என்னை அமரச் செய்தீர்
என் நல்ல தேவன் நீரே
நட்ச்சத்திரம் போல் ஜோலிக்கச் செய்தீர்
என் வல்ல தேவன் நீரே -2
நான் மேலானவைகளை நாடுவேன்
மேன்மையானவையே நோக்குவேன் -2
உமது கிருபை நிமித்தமும்
உமது உண்மையின் நிமித்தமும்
தேவனே உமது நாமத்தை துதிப்பேன்
என்றேன்றும் உமது நாமத்தை துதிப்பேன் -2

**Comment by sskjames** [comment]
Ennai tharukiraen is a different song.
