### ISSUE TITLE
Add the song "Neer Thaan En Thanjamae"

### ISSUE THREAD

**Issue by sskjames** [crunchersaspire/worshipsongs-db-dev#51]
Title: Neer Thaan En Thanjamae
Alternate Title: Neer Than En Thanjame
Author: Robert Roy

**Comment by noahantony** [comment]
{y}நீர் தான் என் தஞ்சமே நீர் தான் என் கோட்டையே{/y}
Neer thaan en thanjsamae neer thaan en koattaiyae

{y}துன்ப வேளை தூக்கி என்னைத் தோளில் சுமந்தவரே{/y}
Thunpa vaelai thookki ennaith thoalil sumanthavarae

{y}உமக்கே ஆராதனை - 2X{/y}
Umakkae aaraathanai - 2X

{y}நீரே என் ஆதாரமே நீரே என் துணையாளரே{/y}
Neerae en aathaaramae neerae en thunaiyaalarae
{y}சோர்ந்திடும் நேரம் சார்ந்திட உந்தன் கிருபை ஈந்தவரே{/y}
Choarnthitum naeram saarnthita unthan kirupai eenthavarae

{y}இயேசுவே உம்மை உயர்த்திடுவேன்{/y}
Yaesuvae ummai uyarththituvaen
{y}என் நேசரே உம்மை பாடிடுவேன்{/y}
En naesarae ummai paatituvaen
{y}நீர் செய்த எல்லா நன்மைக்காக{/y}
Neer cheytha ellaa nanmaikkaaka

{y}உமக்கே ஆராதனை{/y}
Umakkae aaraathanai
{y}நீர் செய்த எல்லா நன்மைக்காக{/y}
Neer cheytha ellaa nanmaikkaaka
{y}உமக்கே ஆராதனை{/y}
Umakkae aaraathanai

{y}உமக்கே ஆராதனை - 4X{/y}
Umakkae aaraathanai - 4X
{y}இயேசுவே உமக்கே ஆராதனை{/y}
Yaesuvae umakkae aaraathanai
{y}உமக்கே ஆராதனை{/y}
Umakkae aaraathanai

**Comment by noahantony** [comment]
Verse order: C1 C2 V1 C2 V2 C3 C4
