### ISSUE TITLE
Add the song "Umathu Kirupaiyinimiththamum"

### ISSUE THREAD

**Issue by sskjames** [crunchersaspire/worshipsongs-db-dev#56]
Title: Umathu Kirupaiyinimiththamum
Alternate Title: Umathu Kirubaiyinimithamum
Author:
Album: Iraivaa

**Comment by Jancy2523** [comment]
உமது கிருபை நிமித்தமும்
Umathu kirupai nimiththamum
உமது உண்மையின் நிமித்தமும்
Umathu unmaiyin nimiththamum
தேவனே உமது நாமத்தை துதிப்பேன்
Thaevanae umathu naamaththai thuthippaen
என்றென்றும் உமது நாமத்தை துதிப்பேன் -2
Entrenrum umathu naamaththai thuthippaen -2

தடைகளை நீக்கும் தளபதியே
Thataikalai neekkum thalapathiyae
என் நல்ல தேவன் நீரே
En nalla thaevan neerae
மதில்களை உடைக்கும் மகத்துவரே
Mathilkalai utaikkum makaththuvarae
என் வல்ல தேவன் நீரே -2
En valla thaevan neerae -2

நான் மேலானவைகளை நாடுவேன்
Naan maelaanavaikalai naatuvaen
மேன்மையானவையே நோக்குவேன் -2
Maenmaiyaanavaiyae noakkuvaen -2

தாழ்ந்த என்னை உயர்த்திடுவீர்
Thaazhnatha ennai uyarththituveer
என் நல்ல தேவன் நீரே
En nalla thaevan neerae
மகிமையின் கணத்தால் முடிசூட்டுவீர்
Makimaiyin kanaththaal mutichoottuveer
என் வல்ல தேவன் நீரே -2
En valla thaevan neerae -2

உன்னதங்களில் என்னை அமரச் செய்தீர்
Unnathangkalil ennai amarach cheytheer
என் நல்ல தேவன் நீரே
En nalla thaevan neerae
நட்ச்சத்திரம் போல் ஜொலிக்கச் செய்தீர்
Natchaththiram poal joalikkach cheytheer
என் வல்ல தேவன் நீரே -2
En valla thaevan neerae -2

**Comment by sskjames** [comment]
Remove extra spaces in verses.
