### ISSUE TITLE
Add the song "Thaevanae Ennai Tharukiraen"

### ISSUE THREAD

**Issue by sskjames** [crunchersaspire/worshipsongs-db-dev#59]
Title: Thaevanae Ennai Tharukiraen
Alternate Title: Thevane Ennai Tharugiren
Author: John Jebaraj
Album: Levi

**Comment by Jancy2523** [comment]
{y}தேவனே என்னை தருகிறேன்{/y}
Thaevanae ennai tharukiraen
{y}உம் பாதத்தில் என்னை படைக்கின்றேன்{/y}
Um paathaththil ennai padaikkintraen
{y}யாவையும் நீர் தந்ததால்{/y}
Yaavaiyum neer thanthathaal
{y}உம்மிடம் திரும்ப தருகின்றேன் -2{/y}
Ummitam thirumpa tharukintraen -2
{y}எந்தன் வாழ்வின் மேன்மை எல்லாம்{/y}
Enthan vaazhvin maenmai ellaam
{y}உந்தனுக்கே தருகிறேன் - 2{/y}
Unthanukkae tharukiraen - 2


{y}எங்கள் ஆராதனை உமக்கே{/y}
Engkal aaraathanai umakkae
{y}எங்கள் வாழ்நாள் எல்லாம் உமக்கே - 2{/y}
Engkal vaazhnaal ellaam umakkae - 2


{y}ஊழியம் நீர் தந்தது{/y}
Oozhiyam neer thanthathu
{y}உயர்வுகள் நீர் தந்தது{/y}
Uyarvukal neer thanthathu
{y}மேன்மைகள் நீர் தந்தது{/y}
Maenmaikal neer thanthathu
{y}செல்வமும் நீர் தந்தது{/y}
Chelvamum neer thanthathu
{y}எந்தன் வாழ்வின் மேன்மை எல்லாம்{/y}
Enthan vaazhvin maenmai ellaam
{y}உந்தனுக்கே தருகிறேன் - 2{/y}
Unthanukkae tharukitraen - 2


{y}தரிசனம் நீர் தந்தது{/y}
Tharisanam neer thanthathu
{y}தாகமும் நீர் தந்தது{/y}
Thaakamum neer thanthathu
{y}கிருபைகள் நீர் தந்தது{/y}
Kirupaikal neer thanthathu
{y}அபிஷேகம் நீர் தந்தது{/y}
Apishaekam neer thanthathu
{y}எந்தன் வாழ்வின் மேன்மை எல்லாம்{/y}
Enthan vaazhvin maenmai ellaam
{y}உந்தனுக்கே தருகிறேன் - 2{/y}
Unthanukkae tharukiraen - 2

**Comment by noahantony** [comment]
---[Verse:1]---
{y}தேவனே என்னை தருகிறேன்{/y}
Thaevanae ennai tharukiraen
{y}உம் பாதத்தில் என்னை படைக்கின்றேன்{/y}
Um paathaththil ennai padaikkintraen
{y}யாவையும் நீர் தந்ததால்{/y}
Yaavaiyum neer thanthathaal
{y}உம்மிடம் திரும்ப தருகின்றேன் -2{/y}
Ummitam thirumpa tharukintraen -2

---[Chorus:1]---
{y}எங்கள் ஆராதனை உமக்கே{/y}
Engkal aaraathanai umakkae
{y}எங்கள் வாழ்நாள் எல்லாம் உமக்கே - 2{/y}
Engkal vaazhnaal ellaam umakkae - 2

---[Chorus:2]—
{y}எந்தன் வாழ்வின் மேன்மை எல்லாம்{/y}
Enthan vaazhvin maenmai ellaam
{y}உந்தனுக்கே தருகிறேன் - 2{/y}
Unthanukkae tharukiraen - 2


---[Verse:2]---
{y}ஊழியம் நீர் தந்தது{/y}
Oozhiyam neer thanthathu
{y}உயர்வுகள் நீர் தந்தது{/y}
Uyarvukal neer thanthathu
{y}மேன்மைகள் நீர் தந்தது{/y}
Maenmaikal neer thanthathu
{y}செல்வமும் நீர் தந்தது{/y}
Chelvamum neer thanthathu


---[Verse:3]---
{y}தரிசனம் நீர் தந்தது{/y}
Tharisanam neer thanthathu
{y}தாகமும் நீர் தந்தது{/y}
Thaakamum neer thanthathu
{y}கிருபைகள் நீர் தந்தது{/y}
Kirupaikal neer thanthathu
{y}அபிஷேகம் நீர் தந்தது{/y}
Apishaekam neer thanthathu

**Comment by noahantony** [comment]
Verse Order: V1 C1 V2 C2 C1 V3 C2 C1

**Comment by sskjames** [comment]
Remove empty spaces. Split verses.
