### ISSUE TITLE
Add the song "Vetrrik Koti Pitiththituvoam"

### ISSUE THREAD

**Issue by Jancy2523** [crunchersaspire/worshipsongs-db-dev#64]

**Comment by Jancy2523** [comment]
Title: Vetrrik Koti Pitiththituvoam
Alternate Title: Vetri Kodi Pidiththiduvom
Author: Fr. S. J Berchmans

**Comment by Jancy2523** [comment]
{y}வெற்றிக் கொடி பிடித்திடுவோம் – நாம்{/y}
Vetrrik koti pitiththituvoam – naam
{y}வீரநடை நடந்திடுவோம்{/y}
Veeranatai natanthituvoam


{y} வெள்ளம்போல சாத்தான் வந்தாலும்{/y}
Vellampoala saaththaan vanthaalum
{y}ஆவிதாமே கொடி பிடிப்பார்{/y}
Aavithaamae koti pitippaar
{y}அஞ்சாதே என் மகனே{/y}
Anjaathae en makanae
{y}நீ அஞ்சாதே என் மகளே{/y}
Nee anjaathae en makalae


{y}ஆயிரம் தான் துன்பம் வந்தாலும்{/y}
Aayiram thaan thunpam vanthaalum
{y}அணுகாது அணுகாது{/y}
Anukaathu anukaathu
{y}ஆவியின் பட்டயம் உண்டு – நாம்{/y}
Aaviyin pattayam untu – naam
{y}அலகையை வென்று விட்டோம்{/y}
Alakaiyai venru vittoam


{y}காடானாலும் மேடானாலும்{/y}
Kaataanaalum maetaanaalum
{y}கர்த்தருக்க பின் நடப்போம்{/y}
Karththarukka pin natappoam
{y}கலப்பையில் கை வைத்திட்டோம்{/y}
Kalappaiyil kai vaiththittoam
{y}நாம் திரும்பி பார்க்க மாட்டோம்{/y}
Naam thirumpi paarkka maattoam


{y}கோலியாத்தை முறியடிப்போம்{/y}
Koaliyaaththai muriyatippoam
{y}இயேசுவின் நாமத்தினால்{/y}
Yaesuvin naamaththinaal
{y}விசுவாச கேடயத்தினால்{/y}
Visuvaasa kaetayaththinaal
{y}பிசாசை வென்றிடுவோம்{/y}
Pisaasai venrituvoam

**Comment by sskjames** [comment]
Remove extra space in verses.

**Comment by sskjames** [comment]
Update alternate title to include (Vettri Kodi) to help users find the song easily.
