### ISSUE TITLE
Add 20 Christmas songs

### ISSUE THREAD

**Issue by noahantony** [crunchersaspire/worshipsongs-db-dev#74]
Add the following very popular Christmas songs:

NOTE: Set the Author as "Author Unknown" and Album as "Christmas Songs".

1. Yesu Palanay Munnanaiyeelay
2. Yesu Rajan Piranthaar
3. Vanthar Karthar Vanthar
4. Athi Kalayil Palanai Thedi
5. Namaskaripom Nam Yesu Rajan
6. Vaanavar Piranthaar
7. Maasila Theva Mainthan Yelaiyin Kolam Kondar
8. Ullam Siriketumay Vinnil Parakatuumay
9. Kartharallavo Maa Maari Yendru Paalan Allavo
10. Theadi Vantha Oli, Yennai Atri Thetra Vantha Oli
11. Chinna Chinna Palagan 
12. Theva Kumaran Yesu
13. Aarparipom Paalan Piranthe Thinam
14. Elai Kolam Eduthavareh Yesu Raja
15. Avaniyiley Avatharithar
16. Seer Yesu Nathan Yendrum
17. Naam Rajathi Rajanukke
18. Piranthar Piranthar
19. Pirantharey Pirantharey Theva Suthan Pirantharey
20. Namakkoru palagan piranthar

**Comment by sskjames** [comment]
Since the scope of this issue is too big, closing it.
