### ISSUE TITLE
Add the song "Yaehoavaa Yeerae"

### ISSUE THREAD

**Issue by sskjames** [crunchersaspire/worshipsongs-db-dev#86]
Title: Yaehoavaa Yeerae
Alternate Title: Yehova Yeere
Author: John Jebaraj
Topic: Worship
Media Url: https://youtu.be/EQXCg_A2IF0

**Comment by noahantony** [comment]
{y}யெகோவாயீரே நீர் என் தேவனாம்{/y}
Yekoavaayeerae neer en thaevanaam 
{y}இனி என்னுள்ளில் கலக்கம் இல்லை{/y}
 Ini ennullil kalakkam illai

{y}ஆராதனை{/y}
Aaraathanai

{y}இனி என்னுள்ளில் கலக்கம் இல்லை{/y}
Ini ennullil kalakkam illai
{y}நீர் எல்லாமே பார்த்துக் கொள்வீர்{/y}
Neer ellaamae paarththuk kolveer

{y}யெகோவா ரஃபா நீர் என் தேவனாம்{/y}
Yekoavaa raஃpaa neer en thaevanaam 
{y}நீர் என் நோய்கள் சுமந்து கொண்டீர்{/y}
 Neer en noaykal sumanthu kondeer

{y}நீர் என் நோய்கள் சுமந்து கொண்டீர்{/y}
Neer en noaykal sumanthu kondeer
 {y}நீர் எந்தன் மருத்துவரே{/y}
 Neer enthan maruththuvarae

{y}யெகோவா ரூவா நீர் என் தேவனாம்{/y}
Yekoavaa roovaa neer en thaevanaam 
{y}என் தேவைகள் நீர் அறிவீர்{/y} 
En thaevaikal neer ariveer

{y}என் தேவைகள் நீர் அறிவீர்{/y}
En thaevaikal neer ariveer 
{y}நீர் எந்தன் நல் மேய்ப்பரே{/y}
 Neer enthan nal maeypparae
